#! /bin/sh
### BEGIN INIT INFO
# Provides:          redisfs.py
# Required-Start:    $all
# Required-Stop:
# Default-Start:    5
# Default-Stop:
# Short-Description: Run /usr/bin/redisfs.py if it exist
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

do_start() {
	if [ -x /usr/bin/redisfs.py ]; then
		echo -n "Starting redisfs.py..."
		redisfs.py localhost 6379 /var/redisfs & 
		[ $? = 0 ] && echo "." || echo "error"
		return 0
	fi
}

case "$1" in
    start)
	do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
